In [6]:
import numpy as np 
a_arr = np.array([[1, 1, 1], [0, 1, 1], [0, 0, 1]])
b_arr = np.array([[7, 5, 3], [0, 7, 5], [0, 0, 7]])
c = b_arr.dot(a_arr) + a_arr.dot(b_arr) 
print(c)

[[14 24 30]
 [ 0 14 24]
 [ 0  0 14]]


In [7]:
import numpy as np 
arr = np.array([[5,0,0,0], [0, -2,0,0],[0,0,3,0],[0,0,0,2]])
power= np.dot(arr,arr)
print(power)


[[25  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0  4]]


In [8]:
matrix_1 = np.array([[3,0,7], [-4,2,3],[-1,1,2]])
matrix_2 = np.array([1,2,4])
matrix_3 = matrix_1.dot(matrix_2)
print(matrix_3) 


[31 12  9]


In [9]:
import numpy as np 
arr_a = np.array([[0, 2, 0], [3, 4, 5], [6, 7, 8]])
a_det = np.linalg.det(arr_a)
print(format(a_det,'.9g')) 


12


In [10]:
import numpy as np 
a_arr = np.array([[2,3,4,1], [1,2,3,4], [3,4,1,2], [4,1,2,3]])
a_det = np.linalg.det(a_arr)
print(format(a_det,'.9g'))


-160


In [11]:
a = np.array([[2, 5, 7], [6, 3, 4], [5, -2, -3]])
a_inv = np.linalg.inv(a) 
print(a_inv)


[[  1.  -1.   1.]
 [-38.  41. -34.]
 [ 27. -29.  24.]]


In [12]:
aa = np.array([[2,-1,3,4], [0,-1,2,1], [1,1,-1,2], [2,3,-5,3]])
rank = np.linalg.matrix_rank(aa) 
print(rank)


4


In [13]:
A = np.matrix('4 1 4; 1 1 2; 2 1 2')
B = np.matrix('-2; -2; 0')
print('A=', A)
print('B=',B)
A_inv = np.linalg.inv(A)
print(A_inv)
X = A_inv.dot(B)
print('X=',X)


A= [[4 1 4]
 [1 1 2]
 [2 1 2]]
B= [[-2]
 [-2]
 [ 0]]
[[ 0.  -1.   1. ]
 [-1.   0.   2. ]
 [ 0.5  1.  -1.5]]
X= [[ 2.]
 [ 2.]
 [-3.]]


In [14]:
a = np.matrix('4 1 4; 1 1 2; 2 1 2') 
b = np.matrix('-2; -2; 0') 
def kram(a,b): 
    det_a = np.linalg.det(a) 
    if det_a != 0: 
       a1 = np.matrix(a) 
       a2 = np.matrix(a) 
       a3 = np.matrix(a) 
       a1[:, 0] = b 
       a2[:, 1] = b 
       a3[:, 2] = b 
       x = np.linalg.det(a1)/det_a 
       y =np.linalg.det(a2)/det_a 
       z= np.linalg.det(a3)/det_a 
       print('Solving a system of linear algebraic equations by Cramer*s method') 
       print('x=',x.round(3),'y=',y.round(3),'z=',z.round(3))  
    else: 
        print('Determinant equals zero, the system has no solutions') 
    return x,y,z 
kram(a,b) 
print('Checking the correctness of the solution\n', np.linalg.solve(a,b).round(3))


Solving a system of linear algebraic equations by Cramer*s method
x= 2.0 y= 2.0 z= -3.0
Checking the correctness of the solution
 [[ 2.]
 [ 2.]
 [-3.]]


In [15]:
a = np.array(np.random.randint(0,5, size=(3,4)))
average_rows = np.mean(a, axis=1)
minimum = np.min(average_rows)
print(a)
print(average_rows)

print('Найнижче середнє значення:', minimum)


[[0 0 0 4]
 [1 3 4 0]
 [1 1 0 2]]
[1. 2. 1.]
Найнижче середнє значення: 1.0
